---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-lynx
# description will be included in the image's metadata
description: bluefin-dx based OS image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    snippets:
      - |
        rpm --import https://downloads.1password.com/linux/keys/1password.asc
        cat > /etc/yum.repos.d/1password.repo << 'EOF'
        [1password]
        name=1Password Stable Channel
        baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
        enabled=1
        gpgcheck=1
        gpgkey=https://downloads.1password.com/linux/keys/1password.asc
        EOF

  - type: rpm-ostree
    install:
      - 1password
      - btop
      - neovim

  - type: brew
    auto-update: true
    brew-analytics: false

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - md.obsidian.Obsidian

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
